### ISSUE TITLE
Flysystem

### ISSUE THREAD

**Issue by miloshavlicek** [jmartin82/virtual-storage#4]
Hi guys, it's really nice and helpful library. However, there is already very used and flexible [Flysystem](http://flysystem.thephpleague.com/) with exactly the same features: [thephpleague/flysystem](https://github.com/thephpleague/flysystem). I do not know whether you know it. If not, you can look at it for inspiration or you can do a plugin with your specific requirements.

**Comment by jmartin82** [comment]
Hi, thanks for your comment.

We are aware of awesome Flysystem and this lib is inspired in it. But we have a bit different goals, we want put more focus on the call strategies and also we want work on homogenise the response from adapters to make our API more clear in some calls.

We are still working on it.

Cheers,
